// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7qdmjhRBYUAZcqDBuKnTGFaJ3lcMb8ZU',
    appId: '1:297109326028:web:3cae9556f0f2f98ec6da69',
    messagingSenderId: '297109326028',
    projectId: 'safe-93f85',
    authDomain: 'safe-93f85.firebaseapp.com',
    storageBucket: 'safe-93f85.firebasestorage.app',
    measurementId: 'G-S45P7LZW2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7qdmjhRBYUAZcqDBuKnTGFaJ3lcMb8ZU',
    appId: '1:297109326028:android:b4f93a058c203ca5c6da69',
    messagingSenderId: '297109326028',
    projectId: 'safe-93f85',
    storageBucket: 'safe-93f85.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7qdmjhRBYUAZcqDBuKnTGFaJ3lcMb8ZU',
    appId: '1:297109326028:android:b4f93a058c203ca5c6da69',
    messagingSenderId: '297109326028',
    projectId: 'safe-93f85',
    storageBucket: 'safe-93f85.firebasestorage.app',
  );
}
